### ISSUE TITLE
Conda Solve Environment - Never stops

### ISSUE THREAD

**Issue by Sam-Malta** [cavineers/Vision2023#1]
When I ran
`pip install ultralytics`
I got an error about how it could not install opencv because opencv was already installed using conda. 

I tried running 
`conda uninstall opencv`
and 
`conda uninstall -c conda-forge opencv`

Both had seemingly looping solve env (gave ample time to solve 30m+). I even reinstalled conda and tried creating a new env, but it remains at solving environment. 

@jcoll3 if we can check it out next Wednesday or Sat that would be great

**Comment by jcoll3** [comment]
I would try downgrading to yolov5, which is still from ultralytics. I'm sure we could figure out v8, but I don't think we don't have enough time in the season. 

Check out the links for yolov5 examples. 

https://towardsdatascience.com/yolov5-object-detection-on-nvidia-jetson-nano-148cfa21a024

https://www.seeedstudio.com/blog/2022/08/23/faster-inference-with-tensorrt-on-nvidia-jetson-run-yolov5-at-27-fps-on-jetson-nano/

The first link has instructions for installing torch vision on a jetson, so maybe try something along those lines first with v8, but plan to fall back to v5 if you hit a road block. 

Will try to make it for about an hour tonight

**Comment by jcoll3** [comment]
@Sammm2607 I see you have it hooked up to the new carrier board. Is it working?

**Comment by Sam-Malta** [comment]
@jcoll3 It looks like nvidia supports onnx runtime (what I'm currently using), and does some optimizations for it already

https://developer.nvidia.com/blog/announcing-onnx-runtime-for-jetson/
